### ISSUE TITLE
[Bug?] Refuses to work outright "overlapping IO operation in progress"

### ISSUE THREAD

**Issue by LillyWho** [71/stadiacontroller#4] opened 2020-12-12 11:27 UTC
Hello there.

I've tried getting this to work, but I can' get it past the following error message where it refuses to work outright:

`2020/12/12 12:24:04 unable to connect to emulated Xbox 360 controller: Overlappe
d I/O operation is in progress.`

When Googling I only find issues related to corrupt .net installations.

Any help would be appreciated. Would be happy to collect further logs if you point me to them.

**Comment by 71** [comment] 2020-12-12 16:57
Mhmm, I really don't know where the issue comes from. The problem either comes from [this line](https://github.com/71/stadiacontroller/blob/d35d8a20be840b6f665e5948256428af918e1189/vigem.go#L183) or [this one](https://github.com/71/stadiacontroller/blob/d35d8a20be840b6f665e5948256428af918e1189/vigem.go#L192), but it doesn't make much sense to me because previous FFI calls have been successfully made before reaching those.

Looking at the [ViGeM code](https://github.com/ViGEm/ViGEmClient/blob/a883c5056add286de11b4ecbbd915fc7e5a7c49d/src/ViGEmClient.cpp#L426), it seems to use "overlapped notifications" behind the scenes but I'm not familiar with those so I don't know what the issue is. Is it possible that another software is accessing ViGeM?

**Comment by LillyWho** [comment] 2020-12-12 17:05
I've installed the ViGeM exclusively for this so I'm sure I haven't anything else that depends on it. Could it be Steam's controller remapping feature clogging up Xinput? I've had issues with controllers in games before due to Steam.

**Comment by nalf3in** [comment] 2020-12-12 22:04
> 
> 
> I've installed the ViGeM exclusively for this so I'm sure I haven't anything else that depends on it. Could it be Steam's controller remapping feature clogging up Xinput? I've had issues with controllers in games before due to Steam.

I got some weird behavior (in my case, the controller was simply not responding to inputs though) with steam remapping thingy. If would suggest closing steam and, if you want a way to see if the controller is still working without a game, typing "Controller" in the Windows search bar should list all connected usb controller and their output. You should see two controllers listed there.

**Comment by LillyWho** [comment] 2020-12-16 18:15
It turns out because I tried it on Windows 7 it didn't work for whatever reason. The controller emulation driver in its latest version on Github (on their build server you can find an msi that won't install on Windows 7 and that doesn't provide the driver on 10 for whatever reason). It does work perfectly on Windows 10 though. It's just a bit of a shame because I don't want to be OS-dependent just to use my controller.

**Comment by 71** [comment] 2020-12-16 21:02
Oh, that's too bad for Win 7. Thanks for letting me know, I'll document that Win 7 is not supported.

Just to be sure, was the Xbox 360 controller installed? The only issue I found related to Win 7 is [this one](https://github.com/ViGEm/ViGEmBus/issues/10#issuecomment-484226080), which mentions that the driver must be installed too.

**Comment by LillyWho** [comment] 2020-12-16 21:10
It definitely was installed and side note, Xbox 360 controllers usually work out of the box on 7. Is there anything you can do or is it due to the emu driver and hence out of your hands?

**Comment by 71** [comment] 2020-12-17 10:01
They do work out of the box, but it could be a trick where the driver isn't installed by default but gets installed when the controller is plugged in for the first time.

In any case, since the error happens within ViGeM I doubt I can do anything about it, sorry.

**Closed by 71** 2020-12-17 10:01 UTC
Labels: bug, help wanted, question

**Comment by Squall-Leonhart** [comment] 2021-06-26 07:48
Windows 7 includes an out of date version of the XUSB driver, the Xbox 360 software for windows 7 has always been needed for SCP and Vigem due to the newer driver it includes, attempting to use either with the inbox driver will fail in various ways one of them being a full lockup of input/output apart from audio.

**Comment by dezorianguy** [comment] 2021-12-22 20:49
Weird, as described here: https://github.com/71/stadiacontroller/issues/13
it all worked perfectly well. I opened the program, cmd window opened, I connected the Stadia Controller and it got recognized. 
But after a fresh Win10 installation the cmd windows just closes immediatly. 

Something is closing that programm...Is there a way to send you logs that document what happens when the program gets executed?
